language: rust
dist: xenial

os:
  - linux
  - osx
  - windows

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

install:
  # Install miri.
  # TODO This will get simpler once rustup 1.17 is release, since miri will be just another component :D
  - rustup toolchain install nightly
  - rustup component add --toolchain nightly rust-src
  - cargo +nightly install --force --git https://github.com/rust-lang/miri miri
  - cargo install xargo

  - rustup component add rustfmt

  - cargo install cargo-deadlinks

script:
  - ./tools/check.sh

after_success:
  test "$TRAVIS_OS_NAME" = linux
  && test "$TRAVIS_RUST_VERSION" = stable
  && sudo apt-get update
  && sudo apt-get install libssl-dev pkg-config cmake zlib1g-dev
  && echo TODO remove the rust flags once tarpaulin is stable.
  && RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin
  && travis_wait ./tools/codecov.sh --xml
  && bash <(curl -s https://codecov.io/bash)
