language: rust
dist: xenial

os:
  - linux
  - osx
  - windows

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: beta
    - rust: nightly

env:
  # Miri breaks frequently so we install it from a specific nightly version.
  - MIRI_TOOLCHAIN=nightly-2019-11-24

install:
  # Install miri.
  # TODO This will eventually be stabilized.
  - rustup toolchain install $MIRI_TOOLCHAIN
  - rustup component add --toolchain $MIRI_TOOLCHAIN miri-preview
  - rustup component add --toolchain $MIRI_TOOLCHAIN rust-src
  - cargo install xargo

  - rustup component add rustfmt

  - cargo install cargo-deadlinks

script:
  - MIRI_TOOLCHAIN=$MIRI_TOOLCHAIN ./tools/check.sh

after_success:
  test "$TRAVIS_OS_NAME" = linux
  && test "$TRAVIS_RUST_VERSION" = stable
  && sudo apt-get update
  && sudo apt-get install libssl-dev pkg-config cmake zlib1g-dev
  && cargo install cargo-tarpaulin
  && travis_wait ./tools/codecov.sh --xml
  && bash <(curl -s https://codecov.io/bash)
